// GENERATED FROM claims_ledger (Supabase project fortify-life-os) 2026-08-11.
// Do not edit claims here: edit the ledger, then regenerate (scripts/gen-evidence.mjs).
// Rows with status 'failed' are excluded by rule; scripts/evidence-check.mjs enforces
// that every key cited by content.js exists here and is verified or corrected.
// Corrected rows carry their CORRECTED text; that is the point of the pipeline.

export const EVIDENCE = {
  "structured-interviews-042": { claim: "Structured interviews rank first in the 2022 corrected re-analysis of selection-method validity, mean operational validity about .42", src: "Sackett PR, Zhang C, Berry CM, Lievens F. J Appl Psychol 2022. PMID 34968080", doi: "10.1037/apl0000994", pop: "meta-analytic matrix across selection predictors", design: "meta-analytic re-analysis", status: "verified", note: "Structure, not questionnaire format, carries assessment validity." },
  "mechanical-vs-clinical-10pct": { claim: "Mechanical combination of recorded information predicts human outcomes about 10% more accurately than expert impressionistic judgment; expert judgment did relatively worse when unstructured interview impressions were included", src: "Grove WM, Zald DH, Lebow BS, Snitz BE, Nelson C. Psychol Assess 2000;12(1):19-30", doi: "10.1037/1040-3590.12.1.19", pop: "136 studies, psychology and medicine", design: "meta-analysis", status: "verified", note: "Why this instrument records ratings and re-compares them mechanically at day 90 instead of trusting recalled impressions." },
  "collaborative-assessment-d042": { claim: "Psychological assessment delivered collaboratively, with feedback discussed together, carries an overall therapeutic effect of d = 0.423; therapy-process effects d = 1.117", src: "Poston JM, Hanson WE. Psychol Assess 2010;22(2):203-212", doi: "10.1037/a0018679", pop: "17 studies, 1,496 participants", design: "meta-analysis", status: "verified", note: "Clinical literature, used as method evidence for drawing the map together. A published comment disputes the attribution, so this is held as supportive, not load-bearing." },
  "cantril-ladder-140-countries": { claim: "The Cantril self-anchoring ladder, a single conversationally administered 0 to 10 self-rating, is collected in 140+ countries by the Gallup World Poll and anchors the World Happiness Report", src: "Cantril H, The Pattern of Human Concerns, 1965; Gallup World Poll methodology", doi: "", pop: "global annual samples, 140+ countries", design: "survey methodology", status: "verified", note: "Self-anchored single-item ratings taken in conversation are validated methodology, not a folk method." },
  "sfbt-scaling-questions": { claim: "The scaling question, a 0 to 10 self-rating followed by exploring what one point higher would look like, is a core technique of solution-focused brief therapy, developed by de Shazer and Berg at the Milwaukee Brief Family Therapy Center", src: "de Shazer S, Berg IK, Milwaukee Brief Family Therapy Center", doi: "", pop: "method literature, brief therapy", design: "technique provenance", status: "verified", note: "Provenance for the follow-up probe form: what would a 7 look like? Method lineage, never a clinical claim." },
  "gas-idiographic-validated": { claim: "Goal Attainment Scaling, in which client and practitioner co-write goal levels and score them together, is a validated idiographic outcome method in rehabilitation and mental health", src: "Kiresuk TJ, Sherman RE. Community Ment Health J 1968;4:443-453; Turner-Stokes L. Clin Rehabil 2009;23(4):362-370", doi: "10.1177/0269215508101742", pop: "rehabilitation and community mental health programs", design: "method literature", status: "verified", note: "The plan's five-level measures are this method: client-set levels, scored together, no instrument administered." },
  "progress-feedback-d014-029": { claim: "Systematic progress feedback in psychotherapy yields small overall gains (d = 0.14) that roughly double for clients going off-track (d = 0.29)", src: "de Jong K, et al. Clin Psychol Rev 2021;85:102002", doi: "10.1016/j.cpr.2021.102002", pop: "58 studies, N = 21,699 patients", design: "multilevel meta-analysis", status: "verified", note: "Psychotherapy evidence, held as adjacent method evidence: brief repeated readings matter mainly for catching drift early." },
  "smd-073": { claim: "Combined physical and psychological interventions: SMD 0.73", src: "Wilkie L, Fisher Z, Geidel A, et al. Nat Hum Behav 2026;10:715-726", doi: "10.1038/s41562-025-02369-1", pop: "183 RCTs, 22,811 participants", design: "network meta-analysis", status: "verified", note: "The anchor study. The pairing is the point: neither side alone matches the pair." },
  "leproult-testosterone": { claim: "One week of five-hour nights lowers daytime testosterone 10 to 15 percent", src: "Leproult R, Van Cauter E. JAMA 2011;305(21):2173-2174", doi: "10.1001/jama.2011.710", pop: "10 healthy men, mean age 24.3", design: "controlled laboratory", status: "verified", note: "Says 10 TO 15 percent, not up to 15. Cortisol did not change in this study. Small study, young men; motivation for the audit, never a diagnosis." },
  "davis-consensus": { claim: "No androgen blood level distinguishes women with and without sexual dysfunction", src: "Davis SR, et al. JCEM 2019;104(10):4660-4666", doi: "10.1210/jc.2019-01603", pop: "global consensus statement", design: "multi-society consensus", status: "verified", note: "Breaks the hormonal link. The mechanism under load is attention and sleep, not a blood level." },
  "heiman-rct": { claim: "Treating only the man improved his untreated partner satisfaction", src: "Heiman JR, et al. BJOG 2007;114(4):437-447", doi: "10.1111/j.1471-0528.2006.01228.x", pop: "176 couples", design: "multicentre double-blind placebo-controlled RCT", status: "verified", note: "The only causal evidence in the spillover literature; it anchors Intimacy Spillover rather than any percentage." },
  "jiann-or-25-33": { claim: "A male partner's erectile difficulty remains a significant risk factor for female sexual difficulty after adjustment", src: "Jiann BP, Su CC, Tsai JY. J Sex Med 2013;10(2):420-429", doi: "10.1111/j.1743-6109.2012.03007.x", pop: "632 sexually active couples, Taiwan", design: "cross-sectional, adjusted", status: "verified", note: "Adjusted, so it survives the obvious confounders. Sample is young for this audience; use for the dynamic." },
  "dubin-2021-blame": { claim: "One in seven women has been blamed by her partner for his erectile difficulty", src: "Dubin JM, Wyant WA, Balaji NC, et al. Sex Med 2021;9(3):100352", doi: "10.1016/j.esxm.2021.100352", pop: "13,617 women, global web survey", design: "cross-sectional convenience survey", status: "verified", note: "Very large N but convenience-recruited; use for the dynamic, never as a prevalence rate." },
  "chew-meta-or3": { claim: "Threefold increase in male sexual dysfunction where the female partner has one", src: "Chew PY, et al. J Sex Med 2021;18(1):99-112", doi: "10.1016/j.jsxm.2020.10.001", pop: "26 studies", design: "systematic review and meta-analysis", status: "verified", note: "OR 3.011. The strongest single piece of dyadic evidence in the file; the dyad moves together in both directions." },
  "cayan-2004-partner-domains": { claim: "Women partnered with men who have ED score lower on arousal, lubrication, orgasm, satisfaction and pain, but not desire; treating the man improves her scores", src: "Cayan S, Bozlu M, Canpolat B, Akbay E. J Sex Marital Ther 2004;30(5):333-341", doi: "10.1080/00926230490465091", pop: "87 women, controlled comparison", design: "prospective controlled comparison", status: "verified", note: "Independent replication of the Heiman result by a different route. Small, single centre, not randomised." },
  "maseroli-2016-partner-hsd": { claim: "Among women already presenting with sexual dysfunction, the male factor that tracks severity is his low desire, not his erectile function", src: "Maseroli E, et al. Andrology 2016;4(5):911-920", doi: "10.1111/andr.12224", pop: "156 women, sexual medicine clinic, Florence", design: "retrospective clinic series, age-adjusted", status: "verified", note: "Desire is the axis in both directions. Male function as perceived by the woman, not measured in him." },
  "shindel-2005-dyad-correlation": { claim: "In matched couples, every male IIEF domain correlates with every female FSFI domain", src: "Shindel A, et al. J Sex Med 2005;2(6):833-841", doi: "10.1111/j.1743-6109.2005.00148.x", pop: "90 couples", design: "retrospective matched-couple correlation", status: "verified", note: "Response rate 8%, which the authors flag themselves. Hold as supporting, not headline." },
  "attachment-r42": { claim: "Attachment anxiety r = .42 with negative mental health; avoidance r = .28", src: "Zhang X, Li J, Xie F, et al. JPSP 2022;123(5):1089-1137", doi: "10.1037/pspp0000437", pop: "224 studies, 79,722 participants", design: "meta-analysis", status: "corrected", note: "The .42 belongs to attachment ANXIETY specifically; avoidance runs .28. The umbrella word is wrong and blurs two patterns. Interpretive lens only, never an intake questionnaire." },
  "cigarettes-15": { claim: "Social disconnection carries mortality impact similar to smoking up to 15 cigarettes a day", src: "Holt-Lunstad J, Smith TB, Layton JB. PLoS Med 2010;7(7):e1000316", doi: "10.1371/journal.pmed.1000316", pop: "148 studies, 308,849 participants", design: "meta-analysis", status: "corrected", note: "Applies to LACKING SOCIAL CONNECTION, not loneliness, and it is UP TO 15. Loneliness alone runs far weaker." },
  "crf-mortality": { claim: "Cardiorespiratory fitness among the strongest predictors of all-cause mortality", src: "Myers J, et al. NEJM 2002;346:793-801; Ross R, et al. Circulation 2016", doi: "10.1056/NEJMoa011858", pop: "6,213 men, prospective cohort", design: "prospective cohort", status: "corrected", note: "AMONG the strongest, never THE strongest: that superlative lives in fitness marketing, not the literature." },
  "ji-exercise-dose": { claim: "Women reached comparable mortality benefit at 140 min/week where men needed 300", src: "Ji H, et al. JACC 2024;83(8):783-793", doi: "10.1016/j.jacc.2023.12.019", pop: "412,413 US adults", design: "prospective cohort", status: "verified", note: "Prescribing a male dose to a woman over-prescribes the work and understates the return." },
  "flourishing-172": { claim: "Only 17.2% of adults are flourishing", src: "Keyes CLM, Mental Health Continuum, MIDUS 1995", doi: "", pop: "n=3,032 US adults 25-74", design: "cross-sectional", status: "verified", note: "12.1% languishing in the same study. Most frameworks cannot see either state." },
  "coaching-g059": { claim: "Coaching: g = 0.59 across 37 randomized controlled trials", src: "de Haan E, Nilsson VO. Acad Manag Learn Educ 2023;22(4):641-661", doi: "10.5465/amle.2022.0107", pop: "37 RCTs, n=2,528", design: "meta-analysis, RCT only", status: "corrected", note: "The number was always real. Abstract concedes publication bias; effects larger with self-reported outcomes." },
  "greendale-cognition": { claim: "Late perimenopausal women stopped showing the practice effect; it returned afterward", src: "Greendale GA, et al. Neurology 2009;72(21):1850-1857", doi: "10.1212/wnl.0b013e3181a71193", pop: "2,362 women, 4 years, SWAN", design: "longitudinal repeated testing", status: "verified", note: "The authors: difficulties may be time-limited. A passage, not a decline. Naming it is the intervention." },
  "lomas-financial-gap": { claim: "Largest male-female flourishing gap of any domain is financial security", src: "Lomas T, Padgett RN, Warren MA, Johnson BR, VanderWeele TJ. Sci Rep 2026", doi: "10.1038/s41598-026-40963-z", pop: "202,898 people, 22 countries", design: "cross-sectional", status: "verified", note: "Money reads as standing, not arithmetic. Male-favouring in 20 of 22 countries." },
  "platt-pay-gap": { claim: "Women earning less than a productivity-matched man: 2.4x odds of major depression", src: "Platt J, Prins S, Bates L, Keyes K. Soc Sci Med 2016;149:1-8", doi: "10.1016/j.socscimed.2015.11.056", pop: "22,581 US workers 30-65", design: "cross-sectional", status: "verified", note: "Where women earned more, the association vanished. Standing, not arithmetic." },
  "covering-67": { claim: "67% of C-suite and senior managers cover identity at work", src: "Deloitte DEI Institute with NYU Meltzer Center, Uncovering culture", doi: "", pop: "US workers", design: "consultancy survey", status: "verified", note: "Consultancy survey, never introduced as research. Pools C-suite, other executives and senior managers." },
  "transparency-72-57": { claim: "Where executives are transparent, 72% of employees report above-average wellbeing vs 57%", src: "Deloitte and Workplace Intelligence, 2022", doi: "", pop: "n=2,100, US/UK/CA/AU", design: "consultancy survey", status: "verified", note: "Cross-sectional self-report; an association, never a cause." },
  "nature-120": { claim: "At least 120 minutes a week in nature associated with good health and wellbeing", src: "White MP, et al. Sci Rep 2019;9:7730", doi: "10.1038/s41598-019-44097-3", pop: "n=19,806", design: "cross-sectional self-report", status: "corrected", note: "Associated with, never produces. The 183-trial meta-analysis found nature-based interventions no better than controls; light exposure carries the stronger evidence." }
};
